env:
  browser: true
  es2024: true
  node: true
  webextensions: true
extends: 
  - standard
  - plugin:unicorn/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - unicorn
globals:
  PREVIEW_URL: readonly
rules:
  unicorn/better-regex: error
  space-before-function-paren:
    - error
    -
      anonymous: always
      named: never
      asyncArrow: always

